# Generated by Django 4.0 on 2021-12-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date_added',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
